{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "demo-api.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "demo-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.ingressNamespace | quote }}
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- if .Values.networkPolicy.allowHttpsEgress }}
    - ports:
        - protocol: TCP
          port: 443
    {{- end }}
{{- end }}
